# Generated by Django 2.2.5 on 2019-09-06 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Registro_ANS', models.CharField(max_length=15)),
                ('Tipo', models.CharField(choices=[('PP', 'PLANO PRIVADO'), ('PU', 'PLANO PUBLICO'), ('PA', 'PARTICULAR'), ('GT', 'GRATUITO'), ('FI', 'FINANCIADO PELO SUS'), ('DP', 'DPVAT')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=50)),
                ('Crm', models.CharField(max_length=14, unique=True)),
                ('Rg', models.CharField(max_length=8, unique=True)),
                ('Cpf', models.CharField(max_length=14, unique=True)),
                ('Especialidade', models.CharField(choices=[('AL', 'Alergia_Imunologia'), ('AN', 'Angiologia'), ('CA', 'Cardiologia'), ('CM', 'Clínica_Médica'), ('DM', 'Dermatologia'), ('EN', 'Endocrinologia'), ('ED', 'Endoscopia'), ('GS', 'Gastroenterologia'), ('GE', 'Geriatria'), ('GI', 'Ginecologia'), ('HE', 'Hematologia'), ('IF', 'Infectologia'), ('MA', 'Mastologia'), ('MT', 'Medicina_do_Trabalho'), ('NF', 'Nefrologia'), ('NE', 'Neurologia'), ('OF', 'Oftalmologia'), ('ON', 'Oncologia'), ('OR', 'Ortopedia'), ('OT', 'Otorrinolaringologia'), ('PE', 'Pediatria'), ('PN', 'Pneumologia'), ('PS', 'Psiquiatria'), ('RA', 'Radiologia'), ('RT', 'Radioterapia'), ('RE', 'Reumatologia'), ('UR', 'Urologia')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_criacao', models.DateField()),
                ('Nome', models.CharField(max_length=100)),
                ('Data_nascimento', models.DateField()),
                ('Naturalidade', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('Cpf', models.CharField(max_length=14, unique=True)),
                ('Rg', models.CharField(max_length=8, unique=True)),
                ('Orgao_emissor', models.CharField(max_length=10)),
                ('Sexo', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMININO'), ('HT', 'HOMEM TRANS'), ('MT', 'MULHER TRANS')], max_length=1)),
                ('Telefone', models.CharField(max_length=15)),
                ('Celular', models.CharField(max_length=15)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Cep', models.CharField(max_length=10)),
                ('Endereco', models.CharField(max_length=100)),
                ('Numero_casa', models.CharField(max_length=10)),
                ('Bairro', models.CharField(max_length=40)),
                ('Cidade', models.CharField(max_length=100)),
                ('Estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('Profissao', models.CharField(blank=True, max_length=50, null=True)),
                ('Estado_civil', models.CharField(choices=[('S', 'SOLTEIRO'), ('C', 'CASADO'), ('D', 'DIVORCIADO'), ('O', 'OUTROS')], max_length=1)),
                ('Pai', models.CharField(blank=True, max_length=100, null=True)),
                ('Mae', models.CharField(max_length=100)),
                ('Pne', models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1)),
                ('Tipo_sanguineo', models.CharField(max_length=4)),
                ('Observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('Numero_receita', models.AutoField(primary_key=True, serialize=False)),
                ('Data_receita', models.DateField(auto_now=True)),
                ('Medicamento', models.CharField(blank=True, max_length=100, null=True)),
                ('Posologia', models.CharField(blank=True, max_length=100, null=True)),
                ('Medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sismedclin.Medico')),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sismedclin.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagem', models.FileField(blank=True, null=True, upload_to='media')),
                ('Data', models.DateField()),
                ('Anotacoes', models.TextField(blank=True, null=True)),
                ('Medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sismedclin.Medico')),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sismedclin.Paciente')),
                ('Receitas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sismedclin.Receita')),
            ],
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('Numero', models.AutoField(primary_key=True, serialize=False, verbose_name='Numero Prontuario')),
                ('Data_abertura', models.DateField(auto_now=True)),
                ('Data_nascimento', models.DateField()),
                ('Endereco', models.CharField(max_length=150, verbose_name='Endereço')),
                ('Telefone', models.CharField(max_length=12)),
                ('Sexo', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMININO'), ('HT', 'HOMEM TRANS'), ('MT', 'MULHER TRANS')], max_length=2)),
                ('Alergia', models.CharField(max_length=5)),
                ('Altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Peso', models.DecimalField(decimal_places=5, max_digits=10)),
                ('Tipo_sanguineo', models.CharField(blank=True, max_length=5, null=True)),
                ('Medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sismedclin.Medico')),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sismedclin.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_vencimento', models.DateField()),
                ('Data_pagamento', models.DateField(blank=True, null=True)),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Status', models.CharField(choices=[('a', 'Apagar'), ('p', 'Pago')], max_length=1)),
                ('Operacao', models.CharField(blank=True, choices=[('DE', 'Debito'), ('CR', 'Credito'), ('DI', 'Dinheiro')], max_length=2)),
                ('descricao', models.TextField(blank=True)),
                ('Paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sismedclin.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField()),
                ('Nascimento', models.DateField()),
                ('Telefone', models.CharField(max_length=20)),
                ('Especialidade', models.CharField(choices=[('AL', 'Alergia_Imunologia'), ('AN', 'Angiologia'), ('CA', 'Cardiologia'), ('CM', 'Clínica_Médica'), ('DM', 'Dermatologia'), ('EN', 'Endocrinologia'), ('ED', 'Endoscopia'), ('GS', 'Gastroenterologia'), ('GE', 'Geriatria'), ('GI', 'Ginecologia'), ('HE', 'Hematologia'), ('IF', 'Infectologia'), ('MA', 'Mastologia'), ('MT', 'Medicina_do_Trabalho'), ('NF', 'Nefrologia'), ('NE', 'Neurologia'), ('OF', 'Oftalmologia'), ('ON', 'Oncologia'), ('OR', 'Ortopedia'), ('OT', 'Otorrinolaringologia'), ('PE', 'Pediatria'), ('PN', 'Pneumologia'), ('PS', 'Psiquiatria'), ('RA', 'Radiologia'), ('RT', 'Radioterapia'), ('RE', 'Reumatologia'), ('UR', 'Urologia')], max_length=2)),
                ('Unidade', models.CharField(max_length=40)),
                ('Status', models.CharField(choices=[('AG', 'AGENDADO'), ('AT', 'ATENDIDO'), ('CA', 'CANCELADO'), ('NC', 'NAO COMPARECEU')], max_length=2)),
                ('Valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sismedclin.Convenio')),
                ('Medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sismedclin.Medico')),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sismedclin.Paciente')),
            ],
        ),
    ]
